/* Auto-generated from .chtml template files -- do not edit.
 * Regenerate: make templates */

#ifndef ZCL_VIEWS_WALLET_TEMPLATES_GEN_H
#define ZCL_VIEWS_WALLET_TEMPLATES_GEN_H

static const char TMPL_SEND_SUCCESS[] =
    "<div class='result-success'>\n<div class='icon'>&#x2713;</div>\n<h2>{{{heading}}}</h2>\n<p>{{{amount}}} ZCL to {{address}}</p>\n{{{txid_html}}}\n<div style='margin-top:24px'>\n<a href='/wallet' style='color:#34d399;font-size:16px'>\nBack to Wallet</a></div></div>\n";

static const char TMPL_TX_ROW[] =
    "<a href='{{{link}}}' style='text-decoration:none;\ncolor:inherit;display:block'>\n<div class='tx-row'>\n<div>\n<span class='tx-amount {{{direction_class}}}'>{{{sign}}}{{{amount}}}</span>\n<span style='color:#888;font-size:14px;\nmargin-left:6px'>ZCL</span></div>\n<div class='tx-meta'>\n<span class='tx-time'{{{time_style}}}>{{{time_label}}}</span>\n<span class='tx-conf'>{{{conf_label}}}</span>\n</div></div></a>\n";

static const char TMPL_HISTORY_HEADER[] =
    "<h2>Transaction History</h2>\n<div class='filter-tabs'>\n<a href='/wallet/history?filter=all' class='{{{all_active}}}'>All ({{{c_all}}})</a>\n<a href='/wallet/history?filter=sent' class='{{{sent_active}}}'>Sent ({{{c_sent}}})</a>\n<a href='/wallet/history?filter=recv' class='{{{recv_active}}}'>Received ({{{c_recv}}})</a>\n</div>\n<input class='search-input' type='text' id='tx-search' \nplaceholder='Search by txid...' value='{{search}}' \naria-label='Search transactions'\nonkeydown='if(event.key===\"Enter\"){\nvar v=this.value.trim();\nwindow.location=\"/wallet/history?filter={{{filter}}}\"+\n(v?\"&amp;q=\"+v:\"\");}'>\n<div class='sub'>{{{count}}} transaction{{{count_plural}}} \n(page {{{page}}} of {{{pages}}})</div>\n";

static const char TMPL_RECEIVE_TABS[] =
    "<div class='tab-toggle'>\n<a id='tab-z' class='active-z' onclick='showTab(\"z\")'>Private</a>\n<a id='tab-t' onclick='showTab(\"t\")'>Public (compatibility)</a>\n</div>\n";

static const char TMPL_VALIDATION_ERROR[] =
    "<div class='result-error'>\n<div class='icon'>&#x2717;</div>\n<h2>{{heading}}</h2>\n<p>{{message}}</p>\n<div style='margin-top:16px;display:flex;gap:16px;justify-content:center'>\n<a href='{{{back_url}}}' style='color:#999'>{{back_label}}</a>\n<a href='{{{retry_url}}}' style='color:#34d399'>Try Again</a>\n</div></div>\n";

static const char TMPL_PAGINATION[] =
    "<div class='page-controls'>\n{{{newer_link}}}\n{{{older_link}}}\n</div>\n";

static const char TMPL_CONF_CONFIRMED[] =
    "<span class='tx-conf'>Block {{{block}}} &middot; {{{confs}}} confs</span>\n";

static const char TMPL_HISTORY_SHIELD[] =
    "<a href='/wallet/tx/{{{txid}}}' style='text-decoration:none;color:inherit'>\n<div class='tx-card' style='border-left-color:#a78bfa'>\n<div style='display:flex;justify-content:space-between;\nalign-items:baseline'>\n<span style='color:#a78bfa;font-weight:700'>\n&#x1F512; Funds Secured</span>\n<span class='pill pill-private'>Secured</span></div>\n<div class='tx-meta'>\n<span class='tx-time' title='{{timestamp}}'>{{{rel_time}}}</span>\n{{{conf_html}}}\n</div></div></a>\n";

static const char TMPL_RECEIVE_ZPANE_CLOSE[] =
    "<div id='copy-msg-z' style='color:#888;font-size:14px;\nmargin-top:4px;height:16px'>Click to copy</div>\n</div>\n";

static const char TMPL_COINS_NO_NOTES[] =
    "<div class='card' style='border-left-color:#f59e0b'>\n<div class='label' style='color:#f59e0b'>\nNo private notes found</div>\n<div style='color:#888;font-size:13px'>\n{{{sapling_keys}}} Sapling keys in wallet. \nRun <code style='color:#f59e0b'>rescanwallet</code> \nto scan the chain for notes belonging to these keys.\n</div></div>\n";

static const char TMPL_CHECKPOINT_ROW[] =
    "<tr><td><a href='/explorer/block/{{{height}}}'>{{{height}}}</a></td>\n<td>{{{time}}}</td>\n<td><code style='word-break:break-all'>{{{hash_short}}}...</code></td>\n<td><code>{{{receipt}}}</code></td></tr>\n";

static const char TMPL_RECEIVE_ZPANE_OPEN[] =
    "<div id='pane-z' style='text-align:center;padding:16px 0'>\n<div class='balance-sub' style='margin-bottom:12px'>\nShare this address to receive ZCL privately</div>\n";

static const char TMPL_SEND_CONFIRM_BUTTONS[] =
    "<div style='display:flex;gap:10px;margin:20px 0'>\n<a href='/wallet/send' class='btn-secondary'\nstyle='flex:1;text-align:center;text-decoration:none;\ndisplay:flex;align-items:center;justify-content:center'>Cancel</a>\n<form method='POST' action='zcl://node/wallet/send/confirm'\nstyle='flex:2;margin:0'>\n<input type='hidden' name='address' value='{{address}}'>\n<input type='hidden' name='amount' value='{{{amount}}}'>\n<button type='submit' class='btn-primary'\n style='background:{{{btn_color}}};color:{{{btn_text}}}'\n id='confirm-btn'>\nConfirm Send</button></form></div>\n<div id='send-loading' class='loading-overlay' style='display:none'>\n<div class='spinner'></div>\n<p>Sending transaction...</p></div>\n<script>\ndocument.getElementById('confirm-btn').addEventListener('click',\nfunction(e){e.preventDefault();this.disabled=true;\ndocument.getElementById('send-loading').style.display='flex';\nthis.form.submit();});\n</script>\n";

static const char TMPL_BACKUP_WARNING[] =
    "<div class='card' style='border-left-color:#f87171;margin:16px 0'>\n<div style='display:flex;align-items:center;gap:8px'>\n<span style='font-size:20px'>&#x26A0;</span>\n<div>\n<div style='color:#f87171;font-weight:700;font-size:14px'>\nWallet Not Backed Up</div>\n<div style='color:#888;font-size:14px'>\nIf you lose this device, your funds are gone forever.</div>\n</div></div>\n<div style='margin-top:10px'>\n<code style='font-size:13px;color:#999'>\nzcl-rpc dumpprivkey {{address}}</code></div>\n</div>\n";

static const char TMPL_NODE_TOR[] =
    "<h3>Tor Hidden Service</h3>\n<div style='background:linear-gradient(135deg,#0a1428,#1a0a28);\nborder:1px solid #2a1a3a;border-radius:10px;padding:16px;margin:8px 0'>\n<div style='display:flex;align-items:center;gap:8px;margin-bottom:8px'>\n<div style='width:8px;height:8px;border-radius:50%;\nbackground:{{{tor_color}}}'></div>\n<span style='color:{{{tor_color}}};font-weight:700;font-size:14px'>\n{{{tor_status}}}</span></div>\n<div class='addr-display-sm' style='color:#a78bfa;font-size:12px'>\n{{{onion_addr}}}</div>\n<div style='color:#666;font-size:13px;margin-top:8px'>\nYour node serves blog, store, and web apps over Tor.\nOnly accessible via .onion address.</div>\n</div>\n";

static const char TMPL_SEND[] =
    "<div style='text-align:center;padding:16px 0'>\n<div style='color:#34d399;font-size:24px;font-weight:700'>\n{{{spendable}}} ZCL</div>\n<div style='color:#888;font-size:14px;margin-top:2px'>\nSpendable balance</div>\n{{{shielded_note}}}\n</div>\n\n<form id='send-form' method='POST' action='zcl://node/wallet/send/review' \nonsubmit='return validateSend()' autocomplete='off'>\n<div class='form-group'>\n<label class='form-label' for='addr'>To</label>\n<input class='form-input' type='text' id='addr' name='address' \nplaceholder='Recipient address (t1... or zs1...)' required \nlist='contacts'>\n<div id='addr-err' class='form-error'></div>\n<div id='privacy-hint' style='font-size:14px;margin-top:4px;\nheight:16px'></div></div>\n\n{{{currency_selector}}}\n\n<div class='form-group'>\n<label class='form-label' for='amt'>Amount</label>\n<div style='display:flex;gap:8px;align-items:center'>\n<input class='form-input' type='text' id='amt' name='amount' \ninputmode='decimal' style='flex:1' placeholder='0.00' required \noninput='updateRemaining()'>\n<button type='button' class='send-max' \nonclick='document.getElementById(\\\"amt\\\").value=\n(BAL-{{{fee}}}).toFixed(8);updateRemaining()'>Max</button></div>\n<div id='remaining' class='remaining' \nstyle='color:#888;font-size:14px;margin:4px 0'></div>\n<div id='amt-err' class='form-error'></div>\n<div style='color:#888;font-size:14px;margin:4px 0'>\nNetwork fee: <span style='color:#f59e0b'>{{{fee}}} ZCL</span>\n</div></div>\n<button type='submit' class='btn-primary' style='margin-top:16px' \nid='review-btn'>Review Send</button>\n</form>\n{{{contacts_datalist}}}\n";

static const char TMPL_SHIELD_INVALID[] =
    "<div class='card' style='border-left-color:#f87171'>\n<div class='label' style='color:#f87171'>Invalid amount</div>\n<a href='/wallet'>Back to Wallet</a></div>\n";

static const char TMPL_HISTORY_CARD[] =
    "<a href='/wallet/tx/{{{txid}}}' style='text-decoration:none;color:inherit'>\n<div class='tx-card' style='border-left-color:{{{color}}}'>\n<div style='display:flex;justify-content:space-between;\nalign-items:baseline'>\n<span class='tx-amount {{{amount_class}}}'>{{{sign}}}{{{amount}}} ZCL</span>\n<span class='pill {{{pill_class}}}'>{{{pill_label}}}</span></div>\n<div class='tx-meta'>\n<span class='tx-time' title='{{timestamp}}'>{{{rel_time}}}</span>\n{{{conf_html}}}\n</div></div></a>\n";

static const char TMPL_NODE_PAGE[] =
    "<h2 style='color:#34d399'>Command Center</h2>\n<div style='color:#888;font-size:14px;margin-bottom:16px'>\nYou are running a sovereign full node on the ZClassic network.</div>\n\n<div class='stats' style='margin-bottom:20px'>\n<div class='stat' style='border-left:3px solid #34d399'>\n<div class='n'>{{{height}}}</div>\n<div class='l'>Block Height</div></div>\n<div class='stat' style='border-left:3px solid #a78bfa'>\n<div class='n' style='color:#a78bfa'>{{{peers}}}</div>\n<div class='l'>Connected Peers</div></div>\n<div class='stat' style='border-left:3px solid #fbbf24'>\n<div class='n' style='color:#fbbf24'>{{{mempool}}}</div>\n<div class='l'>Mempool TXs</div></div>\n<div class='stat' style='border-left:3px solid #60a5fa'>\n<div class='n' style='color:#60a5fa'>{{{difficulty}}}</div>\n<div class='l'>Difficulty</div></div>\n</div>\n\n<h3>Network Status</h3>\n<div class='detail-grid'>\n<div class='lbl'>Sync</div>\n<div class='val'><span class='pill {{{sync_class}}}'>{{{sync_label}}}</span></div>\n<div class='lbl'>Chain</div>\n<div class='val'>ZClassic mainnet (Equihash 192,7)</div>\n<div class='lbl'>Protocol</div>\n<div class='val'>NODE_NETWORK | NODE_BLOOM | NODE_ZCL23</div>\n<div class='lbl'>Version</div>\n<div class='val' style='color:#34d399'>/ZClassic-C23:0.1.0/</div>\n</div>\n\n{{{tor_section}}}\n\n<h3>Connected Peers</h3>\n{{{peer_table}}}\n\n<h3>Mempool</h3>\n<div class='detail-grid'>\n<div class='lbl'>Pending</div>\n<div class='val'>{{{mempool}}} transactions</div>\n<div class='lbl'>UTXO Set</div>\n<div class='val'>{{{utxo_count}}} outputs</div>\n<div class='lbl'>Supply</div>\n<div class='val'>{{{supply}}} ZCL</div>\n</div>\n\n<h3>Quick Actions</h3>\n<div style='display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:8px 0'>\n<a href='/explorer' class='btn-secondary'\n style='text-align:center;padding:12px;font-size:14px'>Block Explorer</a>\n<a href='/wallet/coins' class='btn-secondary'\n style='text-align:center;padding:12px;font-size:14px'>Coin Audit</a>\n<a href='/explorer/tokens' class='btn-secondary'\n style='text-align:center;padding:12px;font-size:14px'>ZSLP Tokens</a>\n<a href='/explorer/stats' class='btn-secondary'\n style='text-align:center;padding:12px;font-size:14px'>Network Stats</a>\n</div>\n";

static const char TMPL_SHIELD_ERROR[] =
    "<div class='result-error'>\n<div class='icon'>&#x26A0;</div>\n<h2>Could Not Secure</h2>\n<p>{{message}}</p>\n<a href='/wallet' style='color:#34d399'>Back to Wallet</a>\n</div>\n";

static const char TMPL_COINS_TOKENS[] =
    "<h3>ZSLP Tokens</h3>\n<div class='overflow-x'><table>\n<tr><th>Token</th><th>Name</th>\n<th>Balance</th></tr>\n{{{token_rows}}}\n</table></div>\n";

static const char TMPL_NODE_PEER_ROW[] =
    "<tr>\n<td class='hash' style='font-size:13px'>{{{addr}}}</td>\n<td><span class='pill {{{dir_class}}}'>{{{direction}}}</span></td>\n<td style='font-size:13px'>{{{subver}}}</td>\n<td style='font-size:13px;color:#888'>{{{height}}}</td>\n</tr>\n";

static const char TMPL_COINS_NOTES_TABLE[] =
    "<div class='overflow-x'>\n<table><tr><th>Amount</th>\n<th>Address</th><th>Count</th><th>Height Range</th></tr>\n{{{note_rows}}}\n<tr class='total-row'>\n<td class='zcl'>{{{z_total}}}</td>\n<td></td>\n<td>{{{z_notes}}} note{{{z_plural}}}</td>\n<td></td></tr></table></div>\n";

static const char TMPL_TX_DETAIL[] =
    "<div style='text-align:center;padding:16px 0'>\n<span class='pill {{{pill_class}}}' style='font-size:13px;padding:4px 12px'>\n{{{direction}}}</span>\n<h2 style='margin:12px 0 4px;color:{{{color}}}'>{{{heading}}}</h2>\n<div class='balance-sub'>{{{rel_time}}} &middot; {{{abs_time}}}</div>\n</div>\n\n<div style='margin:0 0 16px'>\n<div style='display:flex;justify-content:space-between;\nfont-size:13px;color:#888;margin-bottom:4px'>\n<span>{{{confs}}} confirmation{{{conf_plural}}}</span>\n<span>{{{conf_status}}}</span></div>\n<div class='conf-meter'>\n<div class='fill' style='width:{{{conf_pct}}}%;background:{{{conf_color}}}'></div>\n</div></div>\n\n<div class='detail-grid'>\n<div class='lbl'>TxID</div>\n<div class='val'><a href='/explorer/tx/{{{txid}}}' class='hash' \nstyle='font-size:13px'>{{{txid}}}</a></div>\n<div class='lbl'>Block</div>\n<div class='val'>{{{block_height}}}</div>\n<div class='lbl'>Direction</div>\n<div class='val'>{{{direction}}}</div>\n{{{fee_row}}}\n</div>\n\n{{{outputs_section}}}\n\n<div style='text-align:center;margin:24px 0'>\n<a href='/explorer/tx/{{{txid}}}' style='color:#60a5fa;font-size:13px'>\nView full details in Explorer &rarr;</a></div>\n<div style='text-align:center'>\n<a href='/wallet/history' style='color:#34d399;font-size:14px'>\n&larr; Back to History</a></div>\n";

static const char TMPL_PRIVACY_NUDGE[] =
    "<div class='privacy-card' style='display:flex;align-items:center;\ngap:12px;text-align:left'>\n<div style='flex:1'>\n<div class='title' style='margin:0'>{{{amount}}} ZCL publicly visible</div>\n<div class='desc' style='margin:0;margin-top:2px'>\nMake private to unlink from your address</div></div>\n<a class='btn' href='/wallet/shield?all=1' \nstyle='white-space:nowrap;padding:10px 16px'>Secure All</a>\n</div>\n";

static const char TMPL_SHIELD_DONE[] =
    "<div class='privacy-card' style='display:flex;align-items:center;\ngap:12px;text-align:left;border-color:#34d399'>\n<div style='font-size:24px;flex-shrink:0'>&#x2705;</div>\n<div style='flex:1'>\n<div class='title' style='margin:0;color:#34d399'>\nFunds secured!</div>\n<div class='desc' style='margin:0;margin-top:2px'>\nYour ZCL is now private.</div></div></div>\n";

static const char TMPL_RECEIVE_JS[] =
    "<script>\nfunction showTab(t){\ndocument.getElementById('pane-t').style.display=t==='t'?'':'none';\ndocument.getElementById('pane-z').style.display=t==='z'?'':'none';\ndocument.getElementById('tab-t').className=t==='t'?'active':'';\ndocument.getElementById('tab-z').className=t==='z'?'active-z':'';}\n</script>\n";

static const char TMPL_LOADING[] =
    "<div class='empty-state' style='padding:48px 0'>\n<div style='font-size:40px;margin-bottom:12px'>&#x23F3;</div>\n<div style='color:#e2e2e2;font-size:18px;font-weight:600'>\nWallet Loading</div>\n<div style='margin-top:8px'>\nThe database is not yet available.</div>\n</div>\n";

static const char TMPL_SEND_REVIEW[] =
    "<div style='text-align:center;margin-bottom:16px'>\n<span class='form-label'>Review Transaction</span></div>\n<table class='review-table'>\n<tr><td>To</td>\n<td style='color:#60a5fa;font-family:\"JetBrains Mono\",monospace;\nfont-size:14px;word-break:break-all'>{{address}}</td></tr>\n<tr><td>Amount</td>\n<td style='color:#34d399;font-size:18px;font-weight:700'>\n{{{amount}}} ZCL</td></tr>\n<tr><td>Fee</td>\n<td style='color:#999'>{{{fee}}} ZCL</td></tr>\n<tr><td style='font-weight:700'>Total</td>\n<td style='color:#e2e2e2;font-weight:700'>\n{{{total}}} ZCL</td></tr>\n<tr><td>Remaining</td>\n<td style='color:#999'>{{{remaining}}} ZCL</td></tr>\n<tr><td>Privacy</td>\n<td><span class='pill {{{privacy_pill}}}'>{{{privacy_label}}}</span>\n{{{privacy_warning}}}</td></tr>\n<tr><td>Est. Time</td>\n<td style='color:#999'>~2.5 min (1 confirmation)</td></tr>\n</table>\n";

static const char TMPL_COINS_PAGE[] =
    "<h2>Your Coins</h2>\n<div style='color:#6b7280;font-size:13px;margin-bottom:16px'>\nEvery coin in your wallet, verified against the blockchain.</div>\n\n<h3>Public UTXOs (Chain-Verified)</h3>\n<div class='overflow-x'>\n<table><tr><th>Transaction</th><th>Type</th>\n<th>Amount</th><th>Height</th><th>Conf</th></tr>\n{{{utxo_rows}}}\n<tr class='total-row'>\n<td colspan='2'>Total ({{{t_count}}} UTXO{{{t_plural}}})</td>\n<td class='zcl'>{{{t_total}}}</td>\n<td></td><td></td></tr></table></div>\n\n<h3>Private Notes</h3>\n{{{notes_section}}}\n\n<div class='stats' style='margin-top:20px'>\n<div class='stat'>\n<div class='n'>{{{t_total}}}</div>\n<div class='l'>Public</div></div>\n<div class='stat' style='border-color:#a78bfa'>\n<div class='n' style='color:#a78bfa'>{{{z_total}}}</div>\n<div class='l'>Private</div></div>\n<div class='stat' style='border-color:#f59e0b'>\n<div class='n' style='color:#f59e0b'>{{{grand_total}}}</div>\n<div class='l'>Total</div></div>\n</div>\n\n<details style='margin-top:16px'>\n<summary style='color:#999;font-size:13px;font-weight:600;\ntext-transform:uppercase;letter-spacing:.05em;cursor:pointer'>\nDiagnostics &#x25BE;</summary>\n<div class='overflow-x'>\n<table><tr><th>Source</th><th>Balance</th>\n<th>UTXOs</th><th>Status</th></tr>\n<tr><td>Chain UTXO set (chain-verified)</td>\n<td class='zcl'>{{{t_total}}}</td><td>{{{t_count}}}</td>\n<td><span class='pill pill-t'>verified</span></td></tr>\n<tr><td>Cached balance</td>\n<td class='zcl'>{{{speed_bal}}}</td><td>{{{speed_utxos}}}</td>\n<td>{{{diag_status}}}</td></tr>\n</table></div></details>\n\n{{{token_section}}}\n\n<h3>Chain Supply</h3>\n<div class='stats'>\n<div class='stat'>\n<div class='n'>{{{chain_supply}}}</div>\n<div class='l'>UTXO Supply (ZCL)</div></div>\n<div class='stat'>\n<div class='n'>{{{chain_utxos}}}</div>\n<div class='l'>Total UTXOs</div></div>\n</div>\n";

static const char TMPL_TX_INVALID[] =
    "<div class='result-error'>\n<div class='icon'>&#x2717;</div>\n<h2>Invalid Transaction ID</h2>\n<a href='/wallet/history' style='color:#34d399'>Back to History</a>\n</div>\n";

static const char TMPL_RECEIVE_TPANE[] =
    "<div id='pane-t' style='display:none;text-align:center;padding:16px 0'>\n<div class='balance-sub' style='margin-bottom:12px'>\nPublic address &mdash; visible on the blockchain</div>\n{{{qr_svg}}}\n{{{chunked_addr}}}\n<div id='copy-msg' style='color:#888;font-size:14px;\nmargin-top:4px;height:16px'>Click to copy</div>\n<div style='color:#888;font-size:13px;margin-top:2px'>\n<span class='pill pill-t'>Public</span> \nVisible on chain &mdash; use only when required</div>\n</div>\n";

static const char TMPL_SHIELD_CONFIRM[] =
    "<div class='card' style='border-left-color:#a78bfa;padding:20px;\nbackground:linear-gradient(135deg,#141414,#1a1a2a)'>\n<div style='text-align:center'>\n<div style='font-size:14px;color:#888;margin-bottom:8px'>\n&#x1F512; Securing</div>\n<div style='font-size:40px;color:#a78bfa;font-weight:800'>\n{{{amount}}} ZCL</div>\n<div style='color:#888;font-size:14px;margin-top:8px'>\nFee: {{{fee}}} ZCL &middot; Total: {{{total}}} ZCL</div>\n</div></div>\n\n<div class='card'>\n<div style='color:#888;font-size:14px;line-height:1.6'>\n<div style='margin-bottom:8px'>\n<span style='color:#34d399;font-weight:700'>Step 1:</span> \nYour public ZCL moves to a private address (~2.5 min).</div>\n<div style='margin-bottom:8px'>\n<span style='color:#a78bfa;font-weight:700'>Step 2:</span> \nFunds are spendable immediately. For maximum privacy, wait ~6 hours \nso timing analysis cannot link back to the public source.</div>\n<div>\n<span style='color:#60a5fa;font-weight:700'>Step 3:</span> \nSpend from your private balance with no on-chain link to your identity.</div>\n</div></div>\n\n<div style='display:flex;gap:10px;margin:16px 0'>\n<a href='/wallet' class='btn-secondary' \nstyle='flex:1;text-align:center;text-decoration:none;\ndisplay:flex;align-items:center;justify-content:center'>Cancel</a>\n<form method='POST' action='zcl://node/wallet/shield/confirm' \nstyle='flex:2;margin:0'>\n<input type='hidden' name='amount' value='{{{amount}}}'>\n<button type='submit' class='btn-primary' \nstyle='background:#a78bfa;color:#fff'\n id='shield-btn'>Confirm</button></form></div>\n<div id='shield-loading' class='loading-overlay' style='display:none'>\n<div class='spinner'></div>\n<p>Securing funds...</p></div>\n<script>\ndocument.getElementById('shield-btn').addEventListener('click',\nfunction(e){e.preventDefault();this.disabled=true;\ndocument.getElementById('shield-loading').style.display='flex';\nthis.form.submit();});\n</script>\n";

static const char TMPL_CONF_PENDING[] =
    "<span class='tx-conf pill pill-pending' style='font-size:13px'>Pending</span>\n";

static const char TMPL_SHIELD_BALANCE_CARD[] =
    "<div style='margin-top:16px;padding:12px;background:#0a1f14;\nborder-radius:8px'>\n<div style='color:#34d399;font-size:18px;font-weight:700'>\n{{{total}}} ZCL</div>\n<div style='color:#888;font-size:14px;margin-top:4px'>\n{{{transparent}}} public + {{{shielded}}} private</div>\n</div>\n";

static const char TMPL_DASHBOARD[] =
    "<div style='text-align:center;padding:24px 0 16px'>\n<span id='sync' class='pill {{{sync_class}}} sync-badge'>{{{sync_label}}}</span>\n<div id='bal' class='balance' style='margin-top:8px'>\n{{{balance}}} ZCL</div>\n\n<div id='privacy-meter' style='margin:8px auto;max-width:280px'>\n<div style='display:flex;justify-content:space-between;\nfont-size:14px;margin-bottom:4px'>\n<span style='color:{{{pct_color}}}'>{{{pct}}}% private</span>\n<a href='/wallet/coins' style='color:#888;font-size:14px'>\nDetails</a></div>\n<div style='height:6px;background:#1e1e1e;border-radius:3px;\noverflow:hidden'>\n<div id='lock' style='height:100%;width:{{{pct}}}%;background:{{{pct_color}}};\nborder-radius:3px;transition:width .5s'></div>\n</div></div>\n\n<div id='bal-details' style='text-align:center;margin:4px 0'>\n<span id='breakdown' class='balance-sub' style='font-size:14px'>\n{{{breakdown}}}</span></div>\n</div>\n\n<div class='actions'>\n<a href='/wallet/send' class='btn-secondary'\n style='display:flex;align-items:center;justify-content:center'>Send</a>\n<a href='/wallet/receive' class='btn-primary'\n style='display:flex;align-items:center;justify-content:center'>Receive</a>\n</div>\n\n{{{privacy_card}}}\n\n{{{token_cards}}}\n\n<div class='section-header'>\n<span>Recent</span>\n<a href='/wallet/history'>View all</a></div>\n{{{recent_txs}}}\n\n{{{backup_warning}}}\n\n<div class='section-header'>\n<span>Power Node</span>\n<a href='/wallet/node'>Command Center</a></div>\n<a href='/wallet/node' style='text-decoration:none;color:inherit'>\n<div style='background:linear-gradient(135deg,#0a1f14,#0a1428);\nborder:1px solid #1a2a1a;border-radius:10px;padding:14px;margin:4px 0'>\n<div style='display:flex;gap:8px;margin-bottom:8px'>\n<div class='stat' style='flex:1;padding:8px;background:rgba(0,0,0,.3);\nborder:none'>\n<div class='n' style='font-size:18px'>{{{peers}}}</div>\n<div class='l'>Peers</div></div>\n<div class='stat' style='flex:1;padding:8px;background:rgba(0,0,0,.3);\nborder:none'>\n<div class='n' style='font-size:18px'>{{{mempool}}}</div>\n<div class='l'>Mempool</div></div>\n<div class='stat' style='flex:1;padding:8px;background:rgba(0,0,0,.3);\nborder:none'>\n<div class='n' style='font-size:18px;color:{{{node_status_color}}}'>\n{{{node_status}}}</div>\n<div class='l'>Status</div></div>\n</div>\n<div style='display:flex;align-items:center;gap:8px;\nfont-size:13px;color:#888'>\n<div id='tor-dot' style='width:6px;height:6px;border-radius:50%;\nbackground:{{{tor_color}}}'></div>\n<span>{{{tor_label}}}</span>\n<span style='margin-left:auto;color:#60a5fa;font-size:12px'>\nView details &#x2192;</span>\n</div>\n</div></a>\n";

static const char TMPL_RECEIVE_NO_ZADDR[] =
    "<div class='empty-state'>\n<div style='color:#a78bfa;font-size:14px'>\nNo private addresses yet</div>\n<div style='color:#888;font-size:14px;margin-top:4px'>\nGenerate one: <code>zcl-rpc z_getnewaddress</code></div>\n</div>\n";

static const char TMPL_RECEIVE_COPY_JS[] =
    "<script>\ndocument.querySelectorAll('.addr-display,.addr-display-sm,.addr-chunked')\n.forEach(function(el){\nel.style.cursor='pointer';\nel.addEventListener('click',function(){\nvar txt=this.textContent.replace(/\\\\s+/g,'').trim();\nnavigator.clipboard.writeText(txt).then(function(){\nel.style.borderColor='#34d399';\nvar msg=document.getElementById('copy-msg')||\ndocument.getElementById('copy-msg-z');\nvar pz=document.getElementById('pane-z');\nif(pz&&pz.style.display!=='none')\nmsg=document.getElementById('copy-msg-z');\nif(msg)msg.textContent='Copied!';\nsetTimeout(function(){el.style.borderColor='';\nif(msg)msg.textContent='Click to copy';},1500);}\n).catch(function(){\nvar ta=document.createElement('textarea');\nta.value=txt;ta.style.position='fixed';ta.style.left='-9999px';\ndocument.body.appendChild(ta);ta.select();\ndocument.execCommand('copy');document.body.removeChild(ta);\nvar msg=document.getElementById('copy-msg')||\ndocument.getElementById('copy-msg-z');\nvar pz=document.getElementById('pane-z');\nif(pz&&pz.style.display!=='none')\nmsg=document.getElementById('copy-msg-z');\nif(msg)msg.textContent='Copied!';});\n});});\n</script>\n";

static const char TMPL_BACK_TO_WALLET[] =
    "<div style='text-align:center;margin:16px'>\n<a href='/wallet' style='color:#60a5fa;font-size:16px'>\nBack to Wallet</a></div>\n";

static const char TMPL_NODE_NO_TOR[] =
    "<h3>Tor Hidden Service</h3>\n<div style='background:#111;border:1px solid #1e1e1e;\nborder-radius:10px;padding:16px;margin:8px 0'>\n<div style='display:flex;align-items:center;gap:8px'>\n<div style='width:8px;height:8px;border-radius:50%;\nbackground:#666'></div>\n<span style='color:#666;font-weight:700;font-size:14px'>\nNot configured</span></div>\n<div style='color:#555;font-size:13px;margin-top:8px'>\nTor hidden service will start automatically when Tor is available.</div>\n</div>\n";

static const char TMPL_SEND_ERROR[] =
    "<div class='result-error'>\n<div class='icon'>&#x2717;</div>\n<h2>{{{heading}}}</h2>\n<p>{{message}}</p>\n<div style='margin-top:16px;display:flex;gap:16px;justify-content:center'>\n<a href='/wallet' style='color:#999'>Back to Wallet</a>\n<a href='/wallet/send' style='color:#34d399'>Try Again</a>\n</div></div>\n";

static const char TMPL_SHIELD_PENDING[] =
    "<div class='privacy-card' style='display:flex;align-items:center;\ngap:12px;text-align:left;border-color:#a78bfa'>\n<div class='spinner' style='width:24px;height:24px;\nborder:3px solid #333;border-top-color:#a78bfa;\nborder-radius:50%;flex-shrink:0'></div>\n<div style='flex:1'>\n<div class='title' style='margin:0;color:#a78bfa'>\n&#x1F512; Securing funds...</div>\n<div class='desc' style='margin:0;margin-top:2px'>\nYour funds are being made private ({{{elapsed}}} sec ago). \nConfirms in ~2.5 min.</div></div></div>\n";

static const char TMPL_SHIELD_SUCCESS[] =
    "<div class='card' style='border-left-color:#34d399;padding:20px'>\n<div style='text-align:center'>\n<div style='font-size:40px;margin-bottom:8px'>&#x2705;</div>\n<div style='font-size:20px;color:#34d399;font-weight:700'>\n&#x1F512; Funds Secured</div>\n<div style='color:#888;font-size:14px;margin-top:8px'>\n{{{amount}}} ZCL is being made private.</div>\n<div style='color:#888;font-size:14px;margin-top:12px;\nfont-family:monospace;word-break:break-all'>{{opid}}</div>\n<div style='color:#555;font-size:14px;margin-top:12px'>\nSpendable immediately. For maximum privacy, wait ~6 hours \nbefore spending so timing analysis can't link back.</div>\n{{{balance_card}}}\n</div></div>\n";

static const char TMPL_TX_NOT_FOUND[] =
    "<div class='result-warning'>\n<div class='icon'>&#x1F50D;</div>\n<h2>Transaction Not Found</h2>\n<p>This transaction is not in your wallet.</p>\n<a href='/wallet/history' style='color:#34d399'>Back to History</a>\n</div>\n";

static const char TMPL_COINS_NO_TOKENS[] =
    "<h3>ZSLP Tokens</h3>\n<div class='empty-state' style='padding:16px 0'>\nNo tokens held at wallet addresses</div>\n";

static const char TMPL_SHIELD_AMOUNT_FORM[] =
    "<div style='text-align:center;padding:16px 0'>\n<div style='color:#a78bfa;font-size:20px;font-weight:700;\nmargin-bottom:4px'>&#x1F512; Secure Funds</div>\n<div class='balance-sub'>Make your public ZCL private\n&mdash; no longer linked to your address</div></div>\n<form method='GET' action='/wallet/shield'>\n<div class='form-group'>\n<label class='form-label' for='shield-amt'>Amount to Secure</label>\n<div style='display:flex;gap:8px;align-items:center'>\n<input class='form-input' type='text' id='shield-amt'\ninputmode='decimal' name='amount' placeholder='0.00' required>\n<button type='button' class='send-max'\nonclick='document.getElementById(\"shield-amt\").value=\"{{{max_amount}}}\"'>Max</button>\n</div>\n<div style='color:#888;font-size:14px;margin-top:6px'>\nAvailable: <span style='color:#34d399'>{{{available}}} ZCL</span>\n</div></div>\n<div id='shield-err' class='form-error'></div>\n<button type='submit' class='btn-primary'\nstyle='background:#a78bfa;color:#fff;margin-top:8px'\nonclick='var a=parseFloat(document.getElementById(\"shield-amt\").value);if(isNaN(a)||a<=0){document.getElementById(\"shield-err\").textContent=\"Enter a valid amount\";return false;}if(a>{{{max_amount}}}){document.getElementById(\"shield-err\").textContent=\"Insufficient funds\";return false;}'>\nReview</button>\n</form>\n<div style='text-align:center;margin-top:16px'>\n<a href='/wallet' style='color:#888'>Cancel</a></div>\n";

#endif
